About top
anitab-org/anitab-org.github.io pull request #133
Opened 2020-08-16 13:06 UTC by saideepesh000

### Description

Added The Top Section Of About Us Page

Fixes #51 

### Type of Change:

- Code

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
I tested this locally

### Checklist:
**Delete irrelevant options.**

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

2020-08-16 13:11 UTC, saideepesh000 commented
@Sonal240, Please ignore this commit "feat: added top section of aboutus", I forgot to add the package-lock file and the image part the default image is not showing correctly on the website. I mean at the bottom-left of the image we could see the difference. See the image below.

![Screenshot (262)](https://user-images.githubusercontent.com/43727167/90335101-d57ae400-dfef-11ea-9f42-38ff45c97730.png)

2020-09-05 09:38 UTC, annabauza commented
Please prepare testing page by following the guide https://github.com/anitab-org/anitab-org.github.io/wiki/Prepare-testing-GitHub-Pages-for-your-PR

2020-09-05 09:40 UTC, annabauza requested changes

2020-09-05 09:40 UTC, annabauza commented on src/Components/AboutUs/AboutUsSection.js
> +      <Content>
the below looks for me like repeated code, can we generate them using loop?

2020-09-05 15:57 UTC, annabauza approved these changes

2020-09-05 15:58 UTC, merged