Contribute rutvi
anitab-org/anitab-org.github.io pull request #160
Opened 2020-10-29 15:02 UTC by rutvi18

### Description

Include a summary of the change and relevant motivation/context. List any dependencies that are required for this change.

Fixes # [ISSUE]

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
If you are working on a design then add a gif to show the responsiveness of your design.
Please follow [testing guidelines](https://github.com/anitab-org/anitab-org.github.io/wiki/Prepare-testing-GitHub-Pages-for-your-PR) and share the link of deployed site here.

### Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have attached link of deployed site.
- [ ] Any dependent changes have been merged

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

2020-10-30 11:45 UTC, parthsarthiprasad commented
@rutvi18 , thanks for this PR, I was following this issue as well, can you please edit the heading to mention the issue that you are working on and liking it with  "#67" , that'll help reviewers to find out your PR easily as well.Following the template. Thanks.

2020-10-30 11:48 UTC, rutvi18 commented
@parthsarthiprasad do you mean linking to #67 ?

2020-11-07 05:14 UTC, prathmeshkhandelwal1 reviewed
@rutvi18 This PR is giving merge conflict, You should resolve it first. and also plz fill the checklist and types of changes you have done in this PR. You can fill checklist by filling x b/w the brackets `[x]`, And if possible also add ScreenShot of your changes. Feel Free to ask anyone If you stuck anywhere. ;)

2020-12-23 13:01 UTC, annabauza requested changes

2020-12-23 13:01 UTC, annabauza commented on src/content/contributeIntro.json
> +               "par":"bdjbc"
Random text will not be merged, neither Lorem ipsum.

2020-12-26 14:18 UTC, rutvi18 commented
@tichnas I am closing this PR.

2020-12-26 14:18 UTC, closed without merging