[Add] Contribution Ways UI
anitab-org/anitab-org.github.io pull request #162
Opened 2020-11-19 15:50 UTC by tichnas

### Description

Ways to Contribute section (on Contribute page) is added.
The code takes data dynamically from a file `contribution_ways.js`, but the real content is not yet added (#60)

Fixes #66 

### Type of Change:

- Code
- User Interface
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

![Project Name](https://user-images.githubusercontent.com/56799401/99689166-a7a0b200-2aac-11eb-8b21-a8c88d80d151.gif)

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] My changes generate no new warnings

2020-12-22 19:47 UTC, annabauza requested changes
Please replace Lorem ipsum with proper text or rise dependent issue for missing content. Thanks.

2020-12-22 19:47 UTC, annabauza commented on src/content/contribution_ways.js
> +            'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, incidunt veniam dolores id asperiores ad, rerum pariatur eligendi doloremque mollitia quas quis! Reiciendis maiores a
No lorem impsum will be merged

2020-12-22 19:49 UTC, annabauza commented on src/content/contribution_ways.js
> +            'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, incidunt veniam dolores id asperiores ad, rerum pariatur eligendi doloremque mollitia quas quis! Reiciendis maiores a
https://github.com/anitab-org/anitab-org.github.io/pull/181 it seems this PR is about content.

2021-01-02 06:32 UTC, nandini45 commented
@tichnas  can you tell me what changes do u need me to make in my code for the content of this page?

2021-01-02 08:47 UTC, tichnas commented
@nandini45 Thanks for asking. I want the file to be named as `contribution_ways.js` (instead of `contribution_ways.json`). Other than that, it should follow the structure as given here: https://github.com/anitab-org/anitab-org.github.io/blob/3e97ad69f81978b39779d1cdc4be75ed87c780c9/src/content/contribution_ways.js

Some random text is there to get an idea of what to put where, but please let me know if something is not clear.

2021-01-06 12:49 UTC, nandini45 commented
@tichnas  i am a little caught up with my work
 can you do the work?
 i will assign the issue to u.
 you can take my content reformat it the way u want and open a PR
 thank you

2021-01-06 13:34 UTC, tichnas commented
@nandini45 Ok, no issues

2021-01-06 17:53 UTC, Amulya-coder commented
@tichnas Can I work on this issue.

2021-01-06 18:20 UTC, tichnas commented
Hi @Amulya-coder, thanks for your interest in contributing to the community but I already have a PR open for this issue.

2021-01-06 18:26 UTC, tichnas commented
@Amulya-coder By this issue do you mean https://github.com/anitab-org/anitab-org.github.io/issues/60?

2021-01-06 19:40 UTC, Amulya-coder commented
@tichnas Yes ,I want to work on this section but I am pretty new to React-Native. If you don't mind , I can take a little bit more time to develop this than the required time.

2021-01-29 17:45 UTC, Vishal-raj-1 commented
@tichnas Please resolve conflicts !!

2021-02-07 14:20 UTC, annabauza commented
@tichnas I close this PR due to lack of respond.

2021-02-07 14:20 UTC, closed without merging