fix: Added styles for image section.
anitab-org/anitab-org.github.io pull request #170
Opened 2020-11-30 10:11 UTC by nlok5923

### Description
Added styling for scaled image component by wrapping inside view to tackle the cases when image renders on right side.

Fixes #167 

### Type of Change:
**Delete irrelevant options.**

- Code
- User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
If you are working on a design then add a gif to show the responsiveness of your design.
Please follow [testing guidelines](https://github.com/anitab-org/anitab-org.github.io/wiki/Prepare-testing-GitHub-Pages-for-your-PR) and share the link of deployed site here. 
link : https://nlok5923.github.io/anitab-org.github.io/

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have attached link of deployed site.
- [ ] Any dependent changes have been merged

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

2020-11-30 11:41 UTC, tichnas commented on src/Components/ImageContent/index.js
> +    <View style={styles.imageSection}>
Change `styles.imageSection` to `styles.sectionImage`

2020-11-30 11:41 UTC, tichnas commented on src/Components/ImageContent/index.js
>          style={styles.sectionImage}
remove this

2020-11-30 11:43 UTC, tichnas commented on src/Components/ImageContent/index.js
> +    imageSection: {
no need for `imageSection` style

2020-11-30 11:46 UTC, tichnas requested changes
Thanks for the PR :smiley: 
I've requested some changes in `ImageContent` so also do them in the other file. After that everything's perfect.

2020-11-30 12:48 UTC, nlok5923 commented
Thanks @tichnas for requesting changes i had done the said changes please review the pr.

2020-11-30 13:34 UTC, tichnas approved these changes

2020-12-10 21:20 UTC, tichnas requested changes
@nlok5923 Really sorry to request changes again. Just found a small problem in responsiveness with the code.
In the `ImageContent` component, we have to remove `flex: 1` from `styles.sectionImage` (line 58), otherwise responsiveness breaks.

2020-12-11 02:12 UTC, nlok5923 commented
@tichnas it's absolutely fine. I had done the changes requested please review the pr.
Thanks,

2020-12-11 08:34 UTC, tichnas approved these changes

2020-12-22 19:40 UTC, annabauza approved these changes

2020-12-22 19:40 UTC, merged