Create contribute_ways.json
anitab-org/anitab-org.github.io pull request #181
Opened 2020-12-22 06:44 UTC by nandini45

### Description
content for contribution page

Fixes #60 

### Type of Change:
**Delete irrelevant options.**

- Documentation

**Code/Quality Assurance Only**
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] Any dependent changes have been merged

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2020-12-22 15:19 UTC, annabauza reviewed
@nandini45 can you please move this to js file so if we have any images we can load them using require reference?
Thanks.

2020-12-22 15:19 UTC, annabauza commented on src/content/contribute_ways.json
> +                        "par": "Zulip: https://anitab-org.zulipchat.com/#narrow/stream/216321-coding"
please leave the links separately, I don't think we want it as a part of text

2020-12-22 15:52 UTC, tichnas commented
Hi, I've a PR (#162) for the Contribution Ways interface. It'll be great if the content file follows the structure as I've used (https://github.com/anitab-org/anitab-org.github.io/pull/162/files#diff-86f38b9c0acf9cf117ba7949ed1a23cb0872b40f74ac3ee7855c3d45bb5e7ac8) as the code largely depends on that.

If required, I can also do the changes, ie, merge this content and I'll fetch it and re-format it as required.

Sorry for the inconvenience.
Thanks

2020-12-22 16:44 UTC, nandini45 commented
@annabauza ok 
@tichnas ah no issue i can restructure it

2020-12-23 12:59 UTC, annabauza requested changes
as in comment

2021-01-01 13:46 UTC, annabauza commented on src/content/contribute_ways.json
> +                        "par": "Zulip: https://anitab-org.zulipchat.com/#narrow/stream/216321-coding"
@nandini45 can you please fix it?

2021-01-10 07:22 UTC, closed without merging