Added navbar, home page and other routers for the different pages site in reactjs
anitab-org/anitab-org.github.io pull request #217
Opened 2021-02-02 06:21 UTC by Shruti3004

### Description

Fixes #196 

### Type of Change:

- [x] Code
- [x] Quality Assurance
- [x] User Interface

### How Has This Been Tested?
If you are working on a design then add a gif to show the responsiveness of your design.
![Screenshot from 2021-02-02 11-37-26](https://user-images.githubusercontent.com/56133783/106559840-0920da80-654c-11eb-9bb4-27a04b50b6ef.png)
![Screenshot from 2021-02-02 11-37-30](https://user-images.githubusercontent.com/56133783/106559858-0de58e80-654c-11eb-845d-168330743141.png)
![Screenshot from 2021-02-02 11-37-32](https://user-images.githubusercontent.com/56133783/106559866-0f16bb80-654c-11eb-9522-51b27b3f53ee.png)
![Screenshot from 2021-02-02 11-37-35](https://user-images.githubusercontent.com/56133783/106559867-0faf5200-654c-11eb-8ed1-92c4b65c9f45.png)
![Screenshot from 2021-02-02 11-37-40](https://user-images.githubusercontent.com/56133783/106559869-10e07f00-654c-11eb-9fd6-558cd013bf45.png)
![Screenshot from 2021-02-02 11-37-44](https://user-images.githubusercontent.com/56133783/106559882-150c9c80-654c-11eb-97fb-b7ab0f87aaf3.png)

Please follow [testing guidelines](https://github.com/anitab-org/anitab-org.github.io/wiki/Prepare-testing-GitHub-Pages-for-your-PR) and share the link of deployed site here.

### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have attached link of deployed site.
- [x] Any dependent changes have been merged

### Code/Quality Assurance Only:
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been published in downstream modules

2021-02-02 07:58 UTC, Shruti3004 commented
@annabauza Please review!

2021-02-02 13:01 UTC, Shruti3004 commented
@annabauza please have a look over it!

2021-02-03 08:09 UTC, Shruti3004 commented
@annabauza please review!

2021-02-03 19:08 UTC, annabauza requested changes
As we speak. Move it to the top and create wrappers for existing reactjs pages, then use router to display what we have atm. Ones you do that we can start replacing components and pages one by one. What you need to do is make sure router works on static github pages. We tried that before without success.

2021-02-03 19:08 UTC, annabauza commented on reactjs/README.md
> +# Getting Started with Create React App
Do we need this readme?

2021-02-16 21:57 UTC, nandini45 commented
@Shruti3004  can you make the changes as requested?

2021-03-03 16:22 UTC, keshakaneria commented
@Shruti3004 Any updates about the changes requested?

2021-03-03 16:44 UTC, Shruti3004 commented
@keshakaneria I'll be working on it and will make the pr asap

2021-09-14 18:30 UTC, isabelcosta commented
Thank you for your work @Shruti3004 ! Will close due to lack of updates, and make the issue available again.

2021-09-14 18:30 UTC, closed without merging