fix: TITLE 2 instead of proper title in events tab
anitab-org/anitab-org.github.io pull request #221
Opened 2021-02-04 14:40 UTC by Amulya-coder

### Description

Removed TITLE2 and duplicate image as discussed with the mentor

Fixes #199 

### Type of Change:

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
![image](https://user-images.githubusercontent.com/66437295/106906779-88b4d200-6723-11eb-84b1-214fc775c187.png)

### Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings

2021-02-04 14:42 UTC, Amulya-coder commented
@annabauza changes made. Please review it.

2021-02-04 19:23 UTC, annabauza commented on src/content/our_events.js
>              content: [
Delete lines 12 to 18 inclusive, and we will be where we should be. Thanks!

2021-02-04 19:24 UTC, annabauza requested changes
As comment.

2021-02-05 19:26 UTC, annabauza requested changes

2021-02-05 19:26 UTC, annabauza commented on src/content/our_events.js
>              ]
```suggestion
```

2021-02-05 19:26 UTC, annabauza commented on src/content/our_events.js
>          },
```suggestion
```

2021-02-05 19:26 UTC, annabauza commented on src/content/our_events.js
>          {
```suggestion
```

2021-02-05 19:26 UTC, annabauza commented on src/content/our_events.js
>              image:{
```suggestion
```

2021-02-05 19:26 UTC, annabauza commented on src/content/our_events.js
>              },
```suggestion
```

2021-02-05 19:26 UTC, annabauza commented on src/content/our_events.js
>              content: [
```suggestion
```

2021-02-05 19:27 UTC, annabauza commented on src/content/our_events.js
>                  }
```suggestion
                },
```

2021-02-05 19:28 UTC, annabauza commented on src/content/our_events.js
>                  }
```suggestion
                },
```

2021-02-05 19:28 UTC, annabauza approved these changes

2021-02-05 19:29 UTC, annabauza commented
I have made required changes. Thanks.

2021-02-05 19:29 UTC, merged