wrapped the text and icon in a view and made the view clickable
anitab-org/anitab-org.github.io pull request #265
Opened 2021-04-19 20:19 UTC by darshanhande11

### Description
Made the Icon and Text clickable as a whole and changed a bit of styling to make them look clickable.

Fixes #251 

### Type of Change:

- Code
- User Interface

### How Has This Been Tested?
Tested it locally

### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

2021-04-20 02:43 UTC, darshanhande11 commented
@keshakaneria @codesankalp Please review my PR.

2021-04-21 16:01 UTC, keshakaneria requested changes
Can you align them a bit more properly to bring the arrow keys at the center of the text.
(Like "FUTURE ->", the arrow key currently is a bit above from the central horizontal axis of text, we need it to be properly aligned)

2021-04-22 06:54 UTC, darshanhande11 commented
@keshakaneria I have done the suggested change, please review it.

2021-04-22 08:27 UTC, keshakaneria approved these changes
Awesome 🎉Looks great!

2021-04-22 11:19 UTC, devkapilbansal reviewed
@darshanhande11 can you please look into this once? :point_down:

2021-04-22 11:19 UTC, devkapilbansal commented on src/Components/Programs/styles.js
> +    color: '#42aaf5',
Can't we have only one of those as both are same
```suggestion
export const ArrowOutlined = styled(View,{
    color: '#42aaf5',
})
```

2021-04-22 11:19 UTC, devkapilbansal commented on src/Components/Programs/Timeline.js
> +                            </View>
```suggestion
                            <View style={{flexDirection:'row'}}>
                                <View style={{paddingTop: 3}}>
                                    <ArrowOutlined/>
                                </View>
                                <ArrowText>PAST</ArrowText>
                            </View>
```

2021-04-22 11:19 UTC, devkapilbansal commented on src/Components/Programs/Timeline.js
> +                                    <ArrowRightOutlined/>
```suggestion
                                    <ArrowOutlined/>
```

2021-04-22 12:17 UTC, darshanhande11 commented
@devkapilbansal Thank you for suggesting changes! But, `ArrowLeftOutlined` and `ArrowRightOutlined` are two different imports from `ant-design/icons`. To view the import, you can view *line number 5* of `src/Components/Programs/Timeline.js`. `ArrowLeftOutlined` is used for an icon arrow pointing left and the other one is obvious. So, in `styles.css`, I have applied styling for both of them separately. Renaming it to `ArrowOutlined` won't help because both the icons are different and imported separately.

2021-04-22 13:36 UTC, keshakaneria commented
> @devkapilbansal Thank you for suggesting changes! But, `ArrowLeftOutlined` and `ArrowRightOutlined` are two different imports from `ant-design/icons`. To view the import, you can view _line number 5_ of `src/Components/Programs/Timeline.js`. `ArrowLeftOutlined` is used for an icon arrow pointing left and the other one is obvious. So, in `styles.css`, I have applied styling for both of them separately. Renaming it to `ArrowOutlined` won't help because both the icons are different and imported separately.

Absolutely, also @devkapilbansal keeping it different would help us in future if the theme or colors or any sort of UI/UX format is changed, it will be better if separate codesare written to change accordingly. So the current code is fine i guess. What do you say?

2021-04-22 13:41 UTC, devkapilbansal commented
Ohh Okay, I don't know much about frontend :grimacing:

2021-04-25 16:51 UTC, merged

2021-04-25 18:46 UTC, darshanhande11 commented
@annabauza The [suggested changes](https://github.com/anitab-org/anitab-org.github.io/pull/265#pullrequestreview-642075463) weren't supposed to be done as I have explained it [here](https://github.com/anitab-org/anitab-org.github.io/pull/265#issuecomment-824788408).